//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaskSurfPro.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaskSurfPro.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active сonnection.
        /// </summary>
        internal static string ActiveConnection {
            get {
                return ResourceManager.GetString("ActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Surf Pro was designed for devices without root access. That&apos;s why you need to set proxy settings manually. Android doesn&apos;t allow to do it automatically without root access..
        /// </summary>
        internal static string AndroidNotes {
            get {
                return ResourceManager.GetString("AndroidNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous network status.
        /// </summary>
        internal static string AnonymousNetworkStatus {
            get {
                return ResourceManager.GetString("AnonymousNetworkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile internet.
        /// </summary>
        internal static string APN {
            get {
                return ResourceManager.GetString("APN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings..
        /// </summary>
        internal static string APNTip1 {
            get {
                return ResourceManager.GetString("APNTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In &quot;Wireless &amp; Networks&quot; section select &quot;More&quot;..
        /// </summary>
        internal static string APNTip2 {
            get {
                return ResourceManager.GetString("APNTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Mobile networks&quot;..
        /// </summary>
        internal static string APNTip3 {
            get {
                return ResourceManager.GetString("APNTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In popup list select &quot;Access Point Names&quot;..
        /// </summary>
        internal static string APNTip4 {
            get {
                return ResourceManager.GetString("APNTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your mobile internet connection&apos;s name..
        /// </summary>
        internal static string APNTip5 {
            get {
                return ResourceManager.GetString("APNTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;localhost&quot; for &quot;Proxy&quot; field and your Polipo port (default 8000) for &quot;Port&quot; field. It is not necessary to modify the rest fields. Select &quot;Save&quot;..
        /// </summary>
        internal static string APNTip6 {
            get {
                return ResourceManager.GetString("APNTip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply list.
        /// </summary>
        internal static string ApplyList {
            get {
                return ResourceManager.GetString("ApplyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel list.
        /// </summary>
        internal static string CancelList {
            get {
                return ResourceManager.GetString("CancelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities selection cancelled..
        /// </summary>
        internal static string CitiesCancelled {
            get {
                return ResourceManager.GetString("CitiesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities are not selected!.
        /// </summary>
        internal static string CitiesNotSelected {
            get {
                return ResourceManager.GetString("CitiesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities selected, IP addresses added..
        /// </summary>
        internal static string CitiesSelected {
            get {
                return ResourceManager.GetString("CitiesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries selection cancelled..
        /// </summary>
        internal static string CountriesCancelled {
            get {
                return ResourceManager.GetString("CountriesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries are not selected!.
        /// </summary>
        internal static string CountriesNotSelected {
            get {
                return ResourceManager.GetString("CountriesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries selected, IP addresses added..
        /// </summary>
        internal static string CountriesSelected {
            get {
                return ResourceManager.GetString("CountriesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor is copyrighted by The Tor Project. Mask Surf is produced independently from the Tor™ anonymity software and carries no guarantee from The Tor Project about quality, suitability or anything else..
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Downloading network information..
        /// </summary>
        internal static string DownloadWaitMessage {
            get {
                return ResourceManager.GetString("DownloadWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your false IP is.
        /// </summary>
        internal static string FalseIPLabel {
            get {
                return ResourceManager.GetString("FalseIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please get all cities list before modifying selected cities..
        /// </summary>
        internal static string GetCitiesFirst {
            get {
                return ResourceManager.GetString("GetCitiesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain the list of cities.
        /// </summary>
        internal static string GetCitiesList {
            get {
                return ResourceManager.GetString("GetCitiesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain the list of countries.
        /// </summary>
        internal static string GetCountriesList {
            get {
                return ResourceManager.GetString("GetCountriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t obtain license information from Google Play. Check your internet connection and try again..
        /// </summary>
        internal static string GooglePlayNotAvailable {
            get {
                return ResourceManager.GetString("GooglePlayNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglishName {
            get {
                return ResourceManager.GetString("LanguageEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageNativeName {
            get {
                return ResourceManager.GetString("LanguageNativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Surf on social networks.
        /// </summary>
        internal static string MaskSurfOnSocialNetworks {
            get {
                return ResourceManager.GetString("MaskSurfOnSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active connection.
        /// </summary>
        internal static string NoActiveConnection {
            get {
                return ResourceManager.GetString("NoActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not anonymous.
        /// </summary>
        internal static string NotAnonymous {
            get {
                return ResourceManager.GetString("NotAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You application is not licensed or active internet connection is absent. Please connect to the Internet  before starting Mask Surf..
        /// </summary>
        internal static string NotLicensed {
            get {
                return ResourceManager.GetString("NotLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polipo listening port.
        /// </summary>
        internal static string PolipoListeningPort {
            get {
                return ResourceManager.GetString("PolipoListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        internal static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to reset program&apos;s settings..
        /// </summary>
        internal static string ResetAllConfirmation {
            get {
                return ResourceManager.GetString("ResetAllConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to their default values..
        /// </summary>
        internal static string ResetAllDescription {
            get {
                return ResourceManager.GetString("ResetAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all.
        /// </summary>
        internal static string ResetAllLabel {
            get {
                return ResourceManager.GetString("ResetAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected cities.
        /// </summary>
        internal static string SelectedCities {
            get {
                return ResourceManager.GetString("SelectedCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected countries.
        /// </summary>
        internal static string SelectedCountries {
            get {
                return ResourceManager.GetString("SelectedCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected regions.
        /// </summary>
        internal static string SelectedRegions {
            get {
                return ResourceManager.GetString("SelectedRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set it before testing IP to make false IP work..
        /// </summary>
        internal static string SetProxyFirst {
            get {
                return ResourceManager.GetString("SetProxyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were successfully  applied..
        /// </summary>
        internal static string SettingsApplied {
            get {
                return ResourceManager.GetString("SettingsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings weren&apos;t applied. Something went wrong..
        /// </summary>
        internal static string SettingsNotApplied {
            get {
                return ResourceManager.GetString("SettingsNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were reset..
        /// </summary>
        internal static string SettingsWereReset {
            get {
                return ResourceManager.GetString("SettingsWereReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup proxy for mobile internet connection.
        /// </summary>
        internal static string SetupProxyAPN {
            get {
                return ResourceManager.GetString("SetupProxyAPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup proxy for Wi-Fi.
        /// </summary>
        internal static string SetupProxyWifi {
            get {
                return ResourceManager.GetString("SetupProxyWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Connecting to anonymous network..
        /// </summary>
        internal static string StartWaitMessage {
            get {
                return ResourceManager.GetString("StartWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget to switch proxy settings back when Mask Surf Pro is not running..
        /// </summary>
        internal static string SwitchBackWarning {
            get {
                return ResourceManager.GetString("SwitchBackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test IP.
        /// </summary>
        internal static string TestIP {
            get {
                return ResourceManager.GetString("TestIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tor Project disclaimer..
        /// </summary>
        internal static string TheTorProjectDisclaimer {
            get {
                return ResourceManager.GetString("TheTorProjectDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor control port.
        /// </summary>
        internal static string TorControlPort {
            get {
                return ResourceManager.GetString("TorControlPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor listening port.
        /// </summary>
        internal static string TorListeningPort {
            get {
                return ResourceManager.GetString("TorListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor log.
        /// </summary>
        internal static string TorLog {
            get {
                return ResourceManager.GetString("TorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This log contains Tor messages..
        /// </summary>
        internal static string TorLogLabel {
            get {
                return ResourceManager.GetString("TorLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cities:.
        /// </summary>
        internal static string TotalCities {
            get {
                return ResourceManager.GetString("TotalCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total countries:.
        /// </summary>
        internal static string TotalCountries {
            get {
                return ResourceManager.GetString("TotalCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total exit relays:.
        /// </summary>
        internal static string TotalExitRelays {
            get {
                return ResourceManager.GetString("TotalExitRelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total not specified cities:.
        /// </summary>
        internal static string TotalUnknownLocations {
            get {
                return ResourceManager.GetString("TotalUnknownLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet traffic is anonymized..
        /// </summary>
        internal static string TrafficAnonymized {
            get {
                return ResourceManager.GetString("TrafficAnonymized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet traffic is NOT anonymized. Please set proxy settings of active connection to localhost and port 8000..
        /// </summary>
        internal static string TrafficNotAnonymized {
            get {
                return ResourceManager.GetString("TrafficNotAnonymized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your true IP is.
        /// </summary>
        internal static string TrueIPLabel {
            get {
                return ResourceManager.GetString("TrueIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        internal static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to wifi connections list..
        /// </summary>
        internal static string WifiTip1 {
            get {
                return ResourceManager.GetString("WifiTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long tap on your current Wi-Fi connection name..
        /// </summary>
        internal static string WifiTip2 {
            get {
                return ResourceManager.GetString("WifiTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Modify network&quot;..
        /// </summary>
        internal static string WifiTip3 {
            get {
                return ResourceManager.GetString("WifiTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &quot;Show advanced options&quot;..
        /// </summary>
        internal static string WifiTip4 {
            get {
                return ResourceManager.GetString("WifiTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Manual&quot; option for &quot;Proxy&quot; field..
        /// </summary>
        internal static string WifiTip5 {
            get {
                return ResourceManager.GetString("WifiTip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;localhost&quot; for &quot;Proxy hostanme&quot; and your Polipo port (default 8000) for &quot;Proxy port&quot;. It is not necessary to modify the rest fields. Select &quot;Save&quot;..
        /// </summary>
        internal static string WifiTip6 {
            get {
                return ResourceManager.GetString("WifiTip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
